# Generated by Django 3.2.7 on 2023-08-10 05:58

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.CreateModel(
            name='CoursesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
            ],
            options={
                'db_table': 'CoursesDetails',
            },
        ),
    ]
