# Generated by Django 3.2.7 on 2023-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230810_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesdetails',
            name='video_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
