# Generated by Django 3.2.7 on 2023-08-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_coursesdetails_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdetails',
            name='video_link',
            field=models.CharField(max_length=1000),
        ),
    ]
