# Generated by Django 3.2.7 on 2023-08-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_coursesdetails_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('min_description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursesdetails')),
            ],
            options={
                'db_table': 'Playlist',
            },
        ),
    ]
