# Generated by Django 3.2.7 on 2023-08-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesdetails',
            old_name='user',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='coursesdetails',
        ),
    ]
