# Generated by Django 3.2.7 on 2023-08-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230829_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='coursesdetails',
        ),
        migrations.AddField(
            model_name='playlist',
            name='courses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.courses'),
            preserve_default=False,
        ),
    ]
