# Generated by Django 3.2.7 on 2023-08-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230829_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesdetails',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.playlist'),
        ),
    ]
